# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gLhF19nStXPXGTuBpAycgWrceRCGba1S
"""

print("Hola mundo")

pip freeze



import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('./iris.csv')
data.head()

data["Species"].unique()

data.describe()

plt.hist(data.Species)

colnames = data.columns.values.tolist()
predictors = colnames[ :4]
tagert = colnames[4]

print(predictors)

print(tagert)

import numpy as np

data["is train"] = np.random.uniform(0,1, len(data)) <=0.75

data.head

train, test =data[data["is train"] == True], data[data["is train"] == False]

print(len(train))
print(len(test))

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion="entropy", min_samples_split=25, random_state=99)
tree.fit(train[predictors], train[tagert])

preds = tree.predict(test[predictors])

print(preds)

pd.crosstab(test[tagert], preds, rownames=["Actual"], colnames=["Predictions"])

print(3/45)

from sklearn.tree import export_graphviz

with open("./iris_dtree.dot", "w") as dotfile:
  export_graphviz(tree, out_file= dotfile, feature_names = predictors)
  dotfile.close()

import os
from graphviz import Source

file = open("./iris_dtree.dot", "r")
text = file.read()
print(text)

Source(text)

